import Head from 'next/head'
import AuthProtect from "../../components/AuthProtect";
import BasicLayout from "components/layouts/Basic"
import AccountPage from "components/AccountPage"




export default function Account() {
    return (
        <AuthProtect>
            <div>
                <Head>
                    <title>Account Page</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <BasicLayout>
                    <AccountPage />
                </BasicLayout>


            </div>
        </AuthProtect>
    )
}
