import Head from 'next/head'
import BasicLayout from "components/layouts/Basic"
import AccountPage from "components/AccountPage"
import Login from "../../components/Login";




export default function LoginPage() {
    return (
        <div>
            <Head>
                <title>Login Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BasicLayout>
                <Login />
            </BasicLayout>


        </div>
    )
}
