import Head from 'next/head'
import BasicLayout from "components/layouts/Basic"
import ProductPage from "components/ProductPage"
import Axios from "../../helpers/Axios";


export default function Home({product}) {
    return (
        <div>
            <Head>
                <title>Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BasicLayout>
                <ProductPage product={product} />
            </BasicLayout>


        </div>
    )
}
export const getStaticPaths = async () => {

    return {
        paths: [], //indicates that no page needs be created at build time
        fallback: 'blocking' //indicates the type of fallback
    }
}

export async function getStaticProps(context) {
    const {data} = await Axios.get(`/products/${context.params.id}`).catch((err) => {
        return {data:null}
    })
    if(data === null) {
        return {
            redirect: {
                destination: '/404',
                permanent: false,
            },
        }
    }
    return{
        props: {
            product:data
        }
    }
}
