import Head from 'next/head'
import BasicLayout from "components/layouts/Basic"
import ProductsPage from "components/Products"


export default function Home() {
    return (
        <div>
            <Head>
                <title>Products</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BasicLayout>
                <main>
                    <ProductsPage />
                </main>

            </BasicLayout>


        </div>
    )
}
