import Head from 'next/head'
import BasicLayout from "components/layouts/Basic"
import ProductsPage from "components/Products"
import Axios from "helpers/Axios";


export default function Products(props) {
    return (
        <div>
            <Head>
                <title>Products</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BasicLayout>
                <ProductsPage products={props.products} />
            </BasicLayout>


        </div>
    )
}

export async function getStaticProps(context) {
    const {data} = await Axios.get("/products").catch((err) => {
        return {data:[]}
    })
    return {
        props: {products:data}, // will be passed to the page component as props
    }
}