import Head from 'next/head'
import BasicLayout from "components/layouts/Basic"
import OrderPage from "components/OrderPage"


export default function Orders() {
    return (
        <div>
            <Head>
                <title>Ord</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BasicLayout>
                <OrderPage />
            </BasicLayout>


        </div>
    )
}
