import Head from 'next/head'
import BasicLayout from "components/layouts/Basic"
import OrdersPage from "components/OrdersPage"




export default function Orders() {
    return (
        <div>
            <Head>
                <title>Orders</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BasicLayout>
                <main>
                    <OrdersPage />
                </main>

            </BasicLayout>


        </div>
    )
}
